version: '3.8'

services:
  db_core:
    image: postgres:15
    container_name: saqbol_db_core
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data_core:/var/lib/postgresql/data
    networks:
      - lms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  core_service:
    build: ./services/core_service
    container_name: saqbol_core_service
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/core_service:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      db_core:
        condition: service_healthy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db_core
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    networks:
      - lms_network

  ai_service:
    build: ./services/ai_service
    container_name: saqbol_ai_service
    env_file:
      - .env
    volumes:
      - ./services/ai_service:/app
      - ./services/ai_service/logs:/app/logs
    expose:
      - "8000"
    networks:
      - lms_network
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api/
    networks:
      - lms_network

  nginx:
    image: nginx:alpine
    container_name: saqbol_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - core_service
      - ai_service
      - frontend
    networks:
      - lms_network

volumes:
  postgres_data_core:
  static_volume:
  media_volume:

networks:
  lms_network: