version: '3.8'

services:
  # База данных для сервиса авторизации
  db_auth:
    image: postgres:15-alpine
    container_name: saqbol_db_auth
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
    ports:
      - "5433:5432"

  # Наш первый микросервис: Identity & Auth
  auth_service:
    build: ./services/auth_service
    container_name: saqbol_auth_service
    # Команда для запуска сервера внутри контейнера
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/auth_service:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_HOST=db_auth
      - POSTGRES_PORT=5432
    depends_on:
      - db_auth

volumes:
  postgres_data_auth: