global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_core'
    # üî• –í–æ–∑–≤—Ä–∞—â–∞–µ–º /api, —Ç–∞–∫ –∫–∞–∫ –∏–¥–µ–º —á–µ—Ä–µ–∑ Nginx
    metrics_path: '/api/prometheus/metrics'
    static_configs:
      # üî• –°—Ç—É—á–∏–º—Å—è –Ω–µ –≤ core_service, –∞ –≤ Nginx (–ø–æ—Ä—Ç 80)
      - targets: ['nginx:80']